name: Integração Continua

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checando codigo
        uses: actions/checkout@v3

      - name: Using Python3
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.x

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Configurar Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: gusantoz/desafiodevops:latest


  test:
    name: Rodar Testes Unitários
    runs-on: ubuntu-latest

    steps:
      # Baixa o código do repositório para a VM
      - name: Checkout do código
        uses: actions/checkout@v4
          
      # Executa os testes unitários (baseado no seu test_app.py)
      - name: Rodar testes com unittest
        run: python -m unittest test_app.py