name: Integração Continua

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checando codigo
        uses: actions/checkout@v3

      - name: Using Python3
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.x

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Configurar Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: gusantoz/desafiodevops:latest


  test:
    name: Rodar Testes Unitários
    runs-on: ubuntu-latest
    needs: build 

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Using Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.x

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Rodar testes com unittest
        run: python -m unittest test_app.py

  deploy:
    name: Fazer Deploy na Produção
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Deploy no Servidor
        # Action para executar comandos via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}     # IP do meu servidor
          username: ${{ secrets.SERVER_USER }}  # Usuário
          key: ${{ secrets.SERVER_KEY }}      # Chave privada do SSH
          port: 22                            
          script: |
            docker pull gusantoz/desafiodevops:latest
            
            # Para o container antigo (se existir)
            docker stop desafiodevops-container || true
            
            # Remove o container antigo (se existir)
            docker rm desafiodevops-container || true
            
            # Inicia o novo container
            docker run -d -p 80:5000 --name desafiodevops-container gusantoz/desafiodevops:latest